/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    'case-studies': CaseStudy;
    experience: Experience;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * Used in the URL: /blog/<slug>. Leave blank to generate from title.
   */
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover?: (number | null) | Media;
  tags?: string[] | null;
  featured?: boolean | null;
  publishedDate: string;
  updatedDate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Used in the URL: /work/<slug>. Leave blank to generate from title.
   */
  slug: string;
  description: string;
  client?: string | null;
  category: 'build' | 'rebuild' | 'integration' | 'frontend';
  role: string;
  stack?: string[] | null;
  timeframeStart: string;
  /**
   * Leave blank if the engagement is ongoing ("Present").
   */
  timeframeEnd?: string | null;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Lower numbers sort first. Leave blank to sort last.
   */
  order?: number | null;
  links?: {
    github?: string | null;
    live?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  sections: CaseStudySection[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySection".
 */
export interface CaseStudySection {
  sectionTitle: string;
  title?: string | null;
  variant?: ('default' | 'dim' | 'inverted') | null;
  layout?: ('standard' | 'full-width') | null;
  items: (
    | CaseStudyParaBlock
    | CaseStudyNumberedListBlock
    | CaseStudyBulletListBlock
    | CaseStudyEyebrowBlock
    | CaseStudyHeading3Block
    | CaseStudyCodeBlock
    | CaseStudyImageBlock
    | CaseStudySimpleCardBlock
    | CaseStudyChipListBlock
    | CaseStudyStatBlock
    | CaseStudySignatureBlock
    | CaseStudyContainerBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyParaBlock".
 */
export interface CaseStudyParaBlock {
  src: string;
  variant?: ('body' | 'lead') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'para';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyNumberedListBlock".
 */
export interface CaseStudyNumberedListBlock {
  items: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyBulletListBlock".
 */
export interface CaseStudyBulletListBlock {
  items: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'bulletList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyEyebrowBlock".
 */
export interface CaseStudyEyebrowBlock {
  src: string;
  icon?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eyebrow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyHeading3Block".
 */
export interface CaseStudyHeading3Block {
  src: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'h3';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCodeBlock".
 */
export interface CaseStudyCodeBlock {
  src: string;
  language?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyImageBlock".
 */
export interface CaseStudyImageBlock {
  image: number | Media;
  alt: string;
  aspect?: ('square' | 'video') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySimpleCardBlock".
 */
export interface CaseStudySimpleCardBlock {
  chip?: string | null;
  title: string;
  desc: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'simpleCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyChipListBlock".
 */
export interface CaseStudyChipListBlock {
  items: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'chipList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyStatBlock".
 */
export interface CaseStudyStatBlock {
  value: string;
  label: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stat';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySignatureBlock".
 */
export interface CaseStudySignatureBlock {
  name: string;
  role: string;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'signature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContainerBlock".
 */
export interface CaseStudyContainerBlock {
  cols?: ('1' | '2' | '3') | null;
  items: (
    | CaseStudyParaBlock
    | CaseStudyNumberedListBlock
    | CaseStudyBulletListBlock
    | CaseStudyEyebrowBlock
    | CaseStudyHeading3Block
    | CaseStudyCodeBlock
    | CaseStudyImageBlock
    | CaseStudySimpleCardBlock
    | CaseStudyChipListBlock
    | CaseStudyStatBlock
    | CaseStudySignatureBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  company: string;
  position: string;
  /**
   * Earlier titles at this company, oldest first, e.g. "Intern" → "Associate SDE" → "SDE".
   */
  otherPositions?: string[] | null;
  website: string;
  timeframeStart: string;
  /**
   * Leave blank if there is no end date.
   */
  timeframeEnd?: string | null;
  /**
   * Still working here — shows "Present" as the end date, even if an end date is set above.
   */
  ongoing?: boolean | null;
  responsibilities: string[];
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  blogs?: {
    /**
     * Allow clients to find blogs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blogs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blogs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blogs.
     */
    delete?: boolean | null;
  };
  caseStudies?: {
    /**
     * Allow clients to find case-studies.
     */
    find?: boolean | null;
    /**
     * Allow clients to create case-studies.
     */
    create?: boolean | null;
    /**
     * Allow clients to update case-studies.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete case-studies.
     */
    delete?: boolean | null;
  };
  experience?: {
    /**
     * Allow clients to find experience.
     */
    find?: boolean | null;
    /**
     * Allow clients to create experience.
     */
    create?: boolean | null;
    /**
     * Allow clients to update experience.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete experience.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  tags?: T;
  featured?: T;
  publishedDate?: T;
  updatedDate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  client?: T;
  category?: T;
  role?: T;
  stack?: T;
  timeframeStart?: T;
  timeframeEnd?: T;
  coverImage?: T;
  featured?: T;
  order?: T;
  links?:
    | T
    | {
        github?: T;
        live?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  sections?:
    | T
    | {
        section?: T | CaseStudySectionSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySection_select".
 */
export interface CaseStudySectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  title?: T;
  variant?: T;
  layout?: T;
  items?:
    | T
    | {
        para?: T | CaseStudyParaBlockSelect<T>;
        numberedList?: T | CaseStudyNumberedListBlockSelect<T>;
        bulletList?: T | CaseStudyBulletListBlockSelect<T>;
        eyebrow?: T | CaseStudyEyebrowBlockSelect<T>;
        h3?: T | CaseStudyHeading3BlockSelect<T>;
        code?: T | CaseStudyCodeBlockSelect<T>;
        image?: T | CaseStudyImageBlockSelect<T>;
        simpleCard?: T | CaseStudySimpleCardBlockSelect<T>;
        chipList?: T | CaseStudyChipListBlockSelect<T>;
        stat?: T | CaseStudyStatBlockSelect<T>;
        signature?: T | CaseStudySignatureBlockSelect<T>;
        container?: T | CaseStudyContainerBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyParaBlock_select".
 */
export interface CaseStudyParaBlockSelect<T extends boolean = true> {
  src?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyNumberedListBlock_select".
 */
export interface CaseStudyNumberedListBlockSelect<T extends boolean = true> {
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyBulletListBlock_select".
 */
export interface CaseStudyBulletListBlockSelect<T extends boolean = true> {
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyEyebrowBlock_select".
 */
export interface CaseStudyEyebrowBlockSelect<T extends boolean = true> {
  src?: T;
  icon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyHeading3Block_select".
 */
export interface CaseStudyHeading3BlockSelect<T extends boolean = true> {
  src?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCodeBlock_select".
 */
export interface CaseStudyCodeBlockSelect<T extends boolean = true> {
  src?: T;
  language?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyImageBlock_select".
 */
export interface CaseStudyImageBlockSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  aspect?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySimpleCardBlock_select".
 */
export interface CaseStudySimpleCardBlockSelect<T extends boolean = true> {
  chip?: T;
  title?: T;
  desc?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyChipListBlock_select".
 */
export interface CaseStudyChipListBlockSelect<T extends boolean = true> {
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyStatBlock_select".
 */
export interface CaseStudyStatBlockSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySignatureBlock_select".
 */
export interface CaseStudySignatureBlockSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContainerBlock_select".
 */
export interface CaseStudyContainerBlockSelect<T extends boolean = true> {
  cols?: T;
  items?:
    | T
    | {
        para?: T | CaseStudyParaBlockSelect<T>;
        numberedList?: T | CaseStudyNumberedListBlockSelect<T>;
        bulletList?: T | CaseStudyBulletListBlockSelect<T>;
        eyebrow?: T | CaseStudyEyebrowBlockSelect<T>;
        h3?: T | CaseStudyHeading3BlockSelect<T>;
        code?: T | CaseStudyCodeBlockSelect<T>;
        image?: T | CaseStudyImageBlockSelect<T>;
        simpleCard?: T | CaseStudySimpleCardBlockSelect<T>;
        chipList?: T | CaseStudyChipListBlockSelect<T>;
        stat?: T | CaseStudyStatBlockSelect<T>;
        signature?: T | CaseStudySignatureBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  company?: T;
  position?: T;
  otherPositions?: T;
  website?: T;
  timeframeStart?: T;
  timeframeEnd?: T;
  ongoing?: T;
  responsibilities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  blogs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  caseStudies?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  experience?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: string;
  citation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  code: string;
  /**
   * e.g. ts, tsx, bash, css, json
   */
  language?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  headers: {
    label: string;
    id?: string | null;
  }[];
  rows: {
    cells: {
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutGridBlock".
 */
export interface CalloutGridBlock {
  items: {
    heading: string;
    body: string;
    /**
     * Highlight this callout with the accent color.
     */
    accent?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'calloutGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RawHtmlBlock".
 */
export interface RawHtmlBlock {
  /**
   * Escape hatch for one-off embeds (e.g. inline diagrams) that don't fit the standard blocks. Rendered verbatim.
   */
  html: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rawHtml';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}